name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [22.18.0, 22.x, 23.x]
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run format check
        run: pnpm run format:check
      
      - name: Run lint
        run: pnpm run lint
      
      - name: Run type check
        run: pnpm run typecheck
      
      - name: Run tests
        run: pnpm test
      
      - name: Build
        run: pnpm run build
      
      - name: Test CLI help
        run: node dist/index.js --help